name: Terraform Destroy Workflow

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Confirm destroy resources? Type 'yes' to proceed"
        required: true
        default: "no"

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Cambia según tu versión de Terraform

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan (Destroy)
      run: terraform plan -destroy -out=tfplan

    - name: Check confirmation input
      id: check_confirm
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "yes" ]; then
          echo "Destroy was not confirmed. Exiting."
          exit 1
        fi

    - name: Terraform Apply (Destroy)
      if: ${{ steps.check_confirm.outputs.confirm == 'yes' }}
      run: terraform apply -auto-approve tfplan
